### ISSUE TITLE
Original guild to copy does not exist. Please check if the id in the settings is correct.

### ISSUE THREAD

**Issue by havoc137** [Jisagi/Discord-guild-copy#1]
Error: Original guild to copy does not exist. Please check if the id in the settings is correct.

I get this error even though the guild does exist and I am sure I copied the correct id.

**Comment by Jisagi** [comment]
Is the bot, the script is running on, also member of said guild, otherwise it won't work.

**Comment by havoc137** [comment]
That was the issue, the member wasn't in the original guild. Thanks.
