### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by tw0f1sh** [Jisagi/Discord-guild-copy#10]
Hi i have 2 errors while running
first:
"guild.iconURL is not a function"
Screenshot: [https://www1.xup.in/exec/ximg.php?fid=17804031](https://www1.xup.in/exec/ximg.php?fid=17804031)
after that i set the "icon:" as comment with // and run it agan
 
second (after set "icon:" as comment):
"Cannot read property 'bitfield' of undefined"
Screenshot: [https://www1.xup.in/exec/ximg.php?fid=13299693](https://www1.xup.in/exec/ximg.php?fid=13299693)

**Comment by Jisagi** [comment]
Sounds like you installed discord.js with `npm install discord.js`. Please **do not do this**, but only run `npm install` to install the latest master version from the master branch.

Delete `node_modules` and `package-lock.json` and rerun `npm install` and then `node copy.js <argument>`.

**Comment by tw0f1sh** [comment]
it worked thank you sir
