### ISSUE TITLE
Error: INVALID_TOKEN

### ISSUE THREAD

**Issue by jansen-039** [Jisagi/Discord-guild-copy#100]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:**

- Node.js version: 15.8.0
- Operating system: Windows 10

C:\Users\janhe\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133
    const invalidToken = new DJSError(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\janhe\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\janhe\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\client\Client.js:222:21)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

This is my error and I dont know how to fix it. I used 2 tokens and both are not working.

**Comment by Jisagi** [comment]
On the developer page, did you click on the Bot you want to use, then select "Bot" on the left hand side and then use the token to the right of the bots profile picture where it says "Click to Reveal Token"? Otherwise you might have used a key from the "General information" tab. This would be the only thing I can think of why it does not work.
A token looks something like this btw `ODE1NTEzMjEzNzIxNzcyMDM0.YDtf3Q.PsldtWlORRVRPv-bGaOBQkoXMpM` (it's not valid, do don't bother trying this one ;D)

**Comment by jansen-039** [comment]
Hey thanks for your answer. I used account tokens and not bot tokens my mistake. But now i have this error:

>node copy.js clone
nodejs: v15.8.0
C:\Users\janhe\Desktop\discord cloner\node_modules\discord.js\src\client\websocket\WebSocketManager.js:258
        throw new DJSError(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\janhe\Desktop\discord cloner\node_modules\discord.js\src\client\websocket\WebSocketManager.js:258:15)
    at async Client.login (C:\Users\janhe\Desktop\discord cloner\node_modules\discord.js\src\client\Client.js:222:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

**Comment by jansen-039** [comment]
i just want to clone this server: 812818315923816479 to my server

**Comment by Jisagi** [comment]
Check the same page as the token again and scroll down to "Privileged Gateway Intents" and activate both of them. Then it'll work. I should add this to the README eventually :D

**Comment by jansen-039** [comment]
wait the server that i want to copy must be my server? :D

**Comment by Jisagi** [comment]
Not necessarily, but the Bot *has* to be part of the guild/server you want to back/clone.

**Comment by jansen-039** [comment]
"The guildcopy role has to be the highest role on the target guild"

**Comment by Jisagi** [comment]
Read the error again and then check the roles on the target guild

**Comment by jansen-039** [comment]
yes i have the highest role. the last problem i have is how can i get on the server that i want to copy? i mean with my bot account a admin must invite me

**Comment by Jisagi** [comment]
> i mean with my bot account a admin must invite me
Correct. You are not allowed to just randomly copy and server you want to. There is no way around that when using a Bot.
