### ISSUE TITLE
Error :/

### ISSUE THREAD

**Issue by Chadoxi** [Jisagi/Discord-guild-copy#101]
Hey, I have the problem:
![image](https://user-images.githubusercontent.com/65661361/109639646-b5f07680-7b4f-11eb-8e74-d194054f718c.png)

**Comment by Jisagi** [comment]
As long as you have the latest version, this error should not happen anymore. Redownload the repository and try again. I pushed the Intents to the Readme as well jsut now, so it tells you where to enable them for your bot.

**Comment by Chadoxi** [comment]
Okay, but now:
![image](https://user-images.githubusercontent.com/65661361/109669558-7e46f600-7b72-11eb-96bd-82e871f2a0bc.png)
Can we use a client token?

**Comment by Jisagi** [comment]
No, you cannot use a client token. The discord.js library disabled the support for those a long time ago, because Discord themself forbid using those with bot functionality alltogether. You have to use a bot token and the bot must be aprt of the guild you want to backup/clone.
