### ISSUE TITLE
[Outdated] You can use Discord's server templates function now, no need for this

### ISSUE THREAD

**Issue by Jeydin21** [Jisagi/Discord-guild-copy#102]
Discord has server templates that allow you to copy roles, channels, and permissions.

**Comment by Jisagi** [comment]
The library existed before templates where a thing. Should I delete everything just because they do exist now? Not really. If people wanna use it, they can and they are still doing so. You seem to be the only person having a problem with this.

**Comment by successtheman** [comment]
I know I am a bit late, but on top of this, the server templates don't allow you to save the bans, emoji, etc... they are very limited. This is the best option for an all encompassing backup solution for a discord server.
