### ISSUE TITLE
Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by rodas123** [Jisagi/Discord-guild-copy#104]
Language English selected. Translated by Jisagi
Successfully logged in as エロアニメ#5618. Starting script
Latest discord.js version installed
Latest script version installed
1. Serializing general data
2. Serializing role data
3. Serializing category data
4. Serializing text channel data
5. Serializing voice channel data
6. Serializing emojis
7. Serializing bans
8. Saving guild data to file
9. Serialization finished and data successfully saved
10. Deleting channels
11. Deleting roles
12. New guild cleanup finished
13. Setting general data
14. Creating role(s)
Do not know how to serialize a BigInt

- Node.js version:  v14.15.5
- Operating system: win 10 pro
![imagem_2021-04-12_033135](https://user-images.githubusercontent.com/67922665/114333167-96ca0900-9b3f-11eb-944a-9d1bf12da555.png)

**Comment by SmollClover** [comment]
Hey, I've had the same issue and saw that there wasn't a fix yet, so I looked at the Code myself and found a fix that isn't very elegant but at least it makes it work again.

- You need to go into the objects folder and edit the creator.js file
- Once you've opened that, go to scroll down to Line 140 or search for 'Create new role'
- After you found that comment, make a new line underneath it and paste this code on the new line. `BigInt.prototype.toJSON = function() { return this.toString(); };`
- Afterwards, it should look like this
```js
// Create new role
BigInt.prototype.toJSON = function () { return this.toString(); };
let newRole = {
  name: role.name,
  color: role.hexColor,
  hoist: role.hoist,
  mentionable: role.mentionable,
  permissions: BigInt(role.permBitfield),
};
```

And that's it.
Save the file and try again.
Worked perfectly for me and I hope that the creator of this tool will implement a fix of his own.

**Comment by Jisagi** [comment]
Hi, I kinda forgot about the issue still persisted. I'll add the propsed solution to the code soon. I'd rather have it inline, but since d.js seems to shift to bigint ehre and there, this prevents further problems with this completely.

Big thanks to @SmollClover for reminding me again and fixing it as well ❤️
