### ISSUE TITLE
newGuild.fetchBans is not a function

### ISSUE THREAD

**Issue by Cknight70** [Jisagi/Discord-guild-copy#105]
Hi, I've been using your project for well over 2 years now its been very useful.
Today I needed to restore a guild and received the error ``newGuild.fetchBans is not a function``
I have saving bans set to true in the settings.json file and have been backing up the previous guild with this option on.

Here is the full log with debugging on: 
```
connor@tapewormparadise:/mnt/exhdd1tb/Discord-guild-copy$ node copy.js restore DFC
nodejs: v14.15.4
Language English selected. Translated by Jisagi
Successfully logged in as backup bot#xxxx. Starting script
Latest script version installed
1. Serialized data was found and will be used
2. Deleting channels
3. Deleting roles
4. Lifting bans
TypeError: newGuild.fetchBans is not a function
    at /mnt/exhdd1tb/Discord-guild-copy/objects/cleaner.js:56:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Additional information:**

- Node.js version:  nodejs: v14.15.4
- Operating system: Ubuntu Server 20.04

**Comment by Jisagi** [comment]
Yes, that is indeed a bug. I will fix this eitehr today, or over the weekend.

**Comment by Jisagi** [comment]
Should be fixed now with the latest version v1.5.5. If not just reopen the issue.

**Comment by lazibrix** [comment]
> Should be fixed now with the latest version v1.5.5. If not just reopen the issue.

Hello, I just tested and it is not fixed

**Comment by Jisagi** [comment]
> Hello, I just tested and it is not fixed

Did you redownload the script? You can also post the logs the script gave you, that might help resolving it.
I couldn't recreate the issue after the fix anymore.

**Comment by lazibrix** [comment]
> > Hello, I just tested and it is not fixed
> 
> Did you redownload the script? You can also post the logs the script gave you, that might help resolving it.
> I couldn't recreate the issue after the fix anymore.

Yes I redownload the new script and yes : 

`nodejs: v16.4.0
Language English selected. Translated by Jisagi
Successfully logged in as copy paste#1901. Starting script
Latest discord.js version installed
Latest script version installed
1. Serialized data was found and will be used
2. Deleting channels
3. Deleting roles
4. New guild cleanup finished
5. Setting general data
newGuild.setRegion is not a function
PS `C:\Users\brieu\Desktop\Discord-guild-copy-master>``

**Comment by Jisagi** [comment]
Ok, that is also a bug, but a different one. I will open seperate issue for this, since the whole region implementation changed and is now voice channel specific and not guild wide anymore.

**Comment by Jisagi** [comment]
@lazibrix Should be fixed now

**Comment by lazibrix** [comment]
> @lazibrix Should be fixed now

It works perfectly, thank you very much
