### ISSUE TITLE
Client missing intents even though its enabled

### ISSUE THREAD

**Issue by a20kavis** [Jisagi/Discord-guild-copy#108]
I get this error when just trying to do a simple copy. I have enabled intents as seen in the second image, so I dont see why this is happening. I'm aware of the discord templates feature but i am attempting to clone to an already existing server wtih a member base.
![image](https://user-images.githubusercontent.com/81684928/126903389-4c9d5f63-efc8-4299-9936-3c31c09a000c.png)
![image](https://user-images.githubusercontent.com/81684928/126903432-b1733541-1ac6-4ae8-a2b1-f5719fd1d9e2.png)
 I updated node thinking my version was old maybe, but to no avail.

- Node.js version: 14.17.3 LTS
- Operating system: Win 10

**Comment by Jisagi** [comment]
Yes, that is indeed a problem with how they handle Intents now. I won't be able to fix this today, but only in the next few days, depending on how much time I have.

**Comment by Jisagi** [comment]
The latest version fixes should fix the problem you have. Feel free to reopen the issue if it doesn't.
