### ISSUE TITLE
can u help with this please

### ISSUE THREAD

**Issue by Oliverhunt204** [Jisagi/Discord-guild-copy#112]
i added the bot token and still get this 

C:\Users\me\OneDrive\Desktop\Discord-guild-copy-master>node copy.js
C:\Users\me\OneDrive\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\rest\APIRequest.js:33
    agent ??= new https.Agent({ ...this.client.options.http.agent, keepAlive: true });
          ^^^

SyntaxError: Unexpected token '??='
←[90m    at wrapSafe (internal/modules/cjs/loader.js:988:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1036:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:937:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:961:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:92:18)←[39m
    at Object.<anonymous> (C:\Users\me\OneDrive\Desktop\Discord-guild-copy-master\node_modules\←[4mdiscord.js←[24m\src\rest\RESTManager.js:4:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)←[39m

**Comment by Jisagi** [comment]
I am not really sure why this happens, but I suspect it's an outdated version of nodejs. I tested it with v16.6.X withw hich it worked just fine. I pushed a small update just now as well, which fixes some more things. You need to redownload the script and reinstall everything again. Same goes for nodejs, you should check its version by running `node -v` and update to something v16.X.X. If the latter still doesn't fix the problem just let me know.

**Comment by Jaywik7** [comment]
When using "copy.js clone", I get the following message You don't have the latest version of discord.js installed. Please delete the 'node_modules' folder and the 'package-lock.json'/'yarn.lock' and run 'npm install'/'yarn install' again. 

I am using node version 16.6.0, Could someone help?

**Comment by Jisagi** [comment]
@Oliverhunt204 if the provided solution did not resolve the issue feel free to reopen it.
@Jaywik7 see your other issue for more help
