### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by omxpro** [Jisagi/Discord-guild-copy#116]
**Please describe the problem you are having in detail:**

Uhhh idk much about NodeJS but I got a module error
![Screenshot_20211017-184320_Brave](https://user-images.githubusercontent.com/69719569/137628699-2abc26dd-9a7c-4f3c-a08b-ba2cd0a1061f.png)
![Screenshot_20211017-184307_Brave](https://user-images.githubusercontent.com/69719569/137628700-26d9d089-9b9d-4265-97a5-56c9a07d7441.png)

**Additional information:**

- 1.12
- Linux/repl.it

**Comment by omxpro** [comment]
And lemme try it on termux Or UserLAnd (does nodes v16 work on this?)

**Comment by omxpro** [comment]
Can I also use it as a selfbot to copy servers? I really don't care about my disc acc

**Comment by omxpro** [comment]
Wellllll rip

**Comment by Jisagi** [comment]
I will close this issue now. If you still encounter the problem, feel free to reopen it or create a new one.
