### ISSUE TITLE
incessant discord.js issue when attempting a clone

### ISSUE THREAD

**Issue by ThePlagueBoi** [Jisagi/Discord-guild-copy#119]
**Please describe the problem you are having in detail:**

I have been attempting to clone my server, yet keep running into a incessant discord.js issue when attempting a clone.

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

I keep running into the discord.js issue when attempting a clone mentioned in this post here (https://github.com/Jisagi/Discord-guild-copy/issues/113#issue-988407795). I followed the advice to redownload the script and even attempted on a separate computer, as well as using npm install, npm update, and npm install discord.js in multiple different combinations and sequences. I get the same errors on both computers.
![Screenshot 2021-12-20 005100](https://user-images.githubusercontent.com/96408862/146724231-c5ea88e1-d12a-4349-8f3a-2834b888cdd9.png)

**Additional information:**

- Node.js version: v16.13.1
- Operating system: Windows 11 pro & Windows 10 home

**Comment by Jisagi** [comment]
I cannot reproduce the issue you have.
Here are the steps I did:
1. Download the script
2. Run `npm install`
3. Run `node copy.js backup` (Any other command would work as well)

![Console output](https://i.imgur.com/dMbsoe6.png)

Manually installing `discord.js` will not work btw.

**Comment by ThePlagueBoi** [comment]
New script on a different drive, no change in results. Any idea if operating system is an issue?
![Screenshot 2021-12-20 210924](https://user-images.githubusercontent.com/96408862/146864534-e5c5cc07-48d2-4f8a-9c59-66a9c347c735.png)

**Comment by Jisagi** [comment]
I just psuhed a fix, try redownloading and running it again now. Should work now

**Comment by ThePlagueBoi** [comment]
thank you!
