### ISSUE TITLE
Cannot find module 'discord.js' when running copy.js

### ISSUE THREAD

**Issue by a20kavis** [Jisagi/Discord-guild-copy#120]
**Please describe the problem you are having in detail: running node copy.js results in module discord.js not found**

I am trying to run the script just like i have in the past, but i cant get it to work. I have tried to reinstall node and update npm etc. Currently I'm on the latest stable release of node which *should* work but it isnt. I tried downgrading to 16.6 but that didnt let me install discord.js, so i upgraded to 16.9 as it said and then it did install, but then i get the error that it cant find discord.js even though the folder is there in the node_packages

**Additional information:**
I think it has to do with when i run npm install, it always fails on "husky" from what i can understand.. but its done the same on both windows and linux so I am not entirely sure 
`npm ERR! code 1
npm ERR! path /home/pi/Desktop/gc/Discord-guild-copy/node_modules/discord.js
npm ERR! command failed
npm ERR! command sh -c is-ci || husky install
npm ERR! sh: 1: is-ci: not found
npm ERR! .git can't be found (see https://git.io/Jc3F9)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-01-14T14_40_38_569Z-debug-0.log
`

**Edit: getting the exact same error when using yarn install**

error /home/pi/Desktop/gc/Discord-guild-copy/node_modules/discord.js: Command failed.
Exit code: 127
Command: is-ci || husky install
Arguments: 
Directory: /home/pi/Desktop/gc/Discord-guild-copy/node_modules/discord.js
Output:
/bin/sh: 1: is-ci: not found
/bin/sh: 1: husky: not found

**The error from running copy.js**

pi@raspberrypi:~/Desktop/gc/Discord-guild-copy $ node copy.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /home/pi/Desktop/gc/Discord-guild-copy/copy.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/Desktop/gc/Discord-guild-copy/copy.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/Desktop/gc/Discord-guild-copy/copy.js' ]
}

- Node.js version: 16.13.3
- Operating system: Tried on linux and windows with same error

**Comment by Jisagi** [comment]
I just pushed a fix for the issue
