### ISSUE TITLE
everytime i run the npm install command it wont work and just say error 

### ISSUE THREAD

**Issue by wolvesjoint** [Jisagi/Discord-guild-copy#123]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:**

- Node.js version:
- Operating system:

**Comment by wolvesjoint** [comment]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\WINDOWS\system32/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-22T05_39_52_853Z-debug-0.log

C:\WINDOWS\system32>yarn install
'yarn' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\WINDOWS\system32/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-02-22T06_08_20_028Z-debug-0.log

**Comment by Jisagi** [comment]
You cannot run the command inside the "C:\WINDOWS\system32" folder. You have to run it inside the downloaded and extracted Discord-guild-copy folder. Please recheck the "Installation & Usage" part of the Readme

**Comment by Jisagi** [comment]
I will close this issue now. If you still encounter the problem, feel free to reopen it or create a new one.
