### ISSUE TITLE
"Original guild to copy does not exist"

### ISSUE THREAD

**Issue by Bravomanbravo212** [Jisagi/Discord-guild-copy#124]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.
Attempted to copy a discord, (I am not the owner of it), after an attempt to do it several times, I constantly received this error.
```
node copy.js clone
nodejs: v16.13.2
Language English selected. Translated by Jisagi
Successfully logged in as nhcsocopy#9724. Starting script
Latest discord.js version installed
Latest script version installed
Original guild to copy does not exist. Please check if the id in the settings is correct and if the bot is also member of this guild
```

**Additional information:**

- Node.js version: v16.13.2
- Operating system: Windows 10

**Comment by Jisagi** [comment]
Did you make sure, the Bot is a member of the guild you want to backup/clone? If yes, then please try to copy the guild ID again, maybe a copy/paste error occoured.

**Comment by Bravomanbravo212** [comment]
I don't follow, as in inviting the bot into the actual discord?

**Comment by Jisagi** [comment]
Yes correct. The bot, ot rather the account the Bot is using, has to be a member of the guild. You cannot just copy any random guild, because he Bot would not be able to query the information needed.

**Comment by Bravomanbravo212** [comment]
> Yes correct. The bot, ot rather the account the Bot is using, has to be a member of the guild. You cannot just copy any random guild, because he Bot would not be able to query the information needed.

My account is in the discord, but I'm unsure why it actually isn't copying.

**Comment by Jisagi** [comment]
It does not havew to be your account, but the Bot itself. Do you see the Bot on the right hand side in the user list? He has to show up somwhere, otherwise he is not a member of the guild and therefore cannot copy it either.

**Comment by Bravomanbravo212** [comment]
Oh, I'm unsure as to how I'm supposed to invite the bot to the discord as I don't have permissions to invite bots to the discord..?

**Comment by Jisagi** [comment]
Then you will need to ask an Administrator of that server to add the bot for you, otherwise this will not work. Without an "approval" by them adding the bot, you will not be able to copy that, or any other, server.

**Comment by Bravomanbravo212** [comment]
Ah ok, thank you for clearing up the issue.
