### ISSUE TITLE
Backup guild to file: node copy.js backup <backupFile (optional)>

### ISSUE THREAD

**Issue by mrsortie** [Jisagi/Discord-guild-copy#125]
I'm getting an error like this, what could be the reason, thanks
![image](https://user-images.githubusercontent.com/97480310/163715498-56f52ca9-b862-4fca-84fb-24f47b4f036a.png)

**Additional information:**

- Node.js version: Node.js v17.7.1
- Operating system: Windows 11

**Comment by Jisagi** [comment]
It's not an error but the usage instruction how to use which command. There are 3 commands to use which are explained there (backup, restore and clone). Please read what what it says

**Comment by Jisagi** [comment]
Everything at the top whe installing can be ignored, so don't get confused by that. Only what it says after using `node copy.js`

**Comment by Jisagi** [comment]
I will close this issue now. If you still encounter the problem, feel free to reopen it or create a new one.
