### ISSUE TITLE
latest version of discord.js

### ISSUE THREAD

**Issue by Araviz12** [Jisagi/Discord-guild-copy#126]
![image](https://user-images.githubusercontent.com/102819830/166145196-f606c18b-8a9c-495f-bcc0-9e26a52bb46f.png)

ive done what is written, deleted those 2 files and went back to "npm install" but its not working

**Comment by Araviz12** [comment]
it's after ive done node copy.js clone

**Comment by Jisagi** [comment]
That is indeed a bug. I will (finally) remove the check alltogether. I wanted to use a fixed version since v12 of discord.js, so I will set it right now to the current v14 dev version and update it periodically but manually. I will push a commit in a bit to fix this.

**Comment by Jisagi** [comment]
Fixed now ~
