### ISSUE TITLE
Not Copying Channel and Category Permissions

### ISSUE THREAD

**Issue by shubhamshah02** [Jisagi/Discord-guild-copy#127]
**Please describe the problem you are having in detail:**
I saved a backup of my server to a file and restored it. The server name, roles, channels, and categories were all restored with the exception of channel-specific role permissions and category-specific role permissions which are the most tedious to setup manually. Should the bot be copying this over or is this not a feature yet?

**Additional information:**

- Node.js version: v16.15.0
- Operating system: macOS Monterey 12.3.1

**Comment by Jisagi** [comment]
I just pushed a version, which should fix this bug.
