### ISSUE TITLE
Unable to restore guild from file

### ISSUE THREAD

**Issue by MorganMcConville** [Jisagi/Discord-guild-copy#128]
I began by creating a guild, inviting the bot as admin and creating a backup.
I then made some changes to the guild and attempted to restore from the backup

`_node copy.js restore guildData.json_`

The above command implies that one server can be restored from json, however when attempting to do so i get the following error:

_The bot needs to be a member on the new guild_

So, thinking i have to add the guildId to the **newGuildId** setting i get the following error:

_New and old guild cannot be the same_

It seems to me this is not the way you intended "**restore from file**" to work unless I am mistaken

**Additional information:**

- Node.js version: 16.14.2
- Operating system: Windows 11

**Comment by Jisagi** [comment]
The check, that both guild id in the settings file cannot be the same is a security measure I added, so people don't accidentally overwrite the guild they try to backup. You just have to leave the `originalGuildId` blank or put in anything you want. The restore option will then ignore it completely and restore the guild to itself.

**Comment by Jisagi** [comment]
I will close this issue now. If you still encounter the problem, feel free to reopen it or create a new one.
