### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Patrykez76** [Jisagi/Discord-guild-copy#129]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:**

Usage:
  * Backup guild to file: node copy.js backup <backupFile (optional)>
  * Restore guild from file: node copy.js restore <backupFile (optional)>
  * Clone guild to guild: node copy.js clone

- Node.js version:
- Operating system:

**Comment by Jisagi** [comment]
Please read what is says. It did print you the three possible usages the script offers, which you can use
