### ISSUE TITLE
"Please check if the new guild id in the settings is valid"

### ISSUE THREAD

**Issue by CakeArmy** [Jisagi/Discord-guild-copy#13]
Hi, I am sure the guild ID is valid. I have tried both creating a server under a different account and giving the bot user FULL access, and having the bot user own its own discord and copy id that way. Not sure at all what the problem is.

https://gyazo.com/2d30ba2dfc8f60a32b99d6fa859c1aea

**Comment by CakeArmy** [comment]
Tried to add the role-id by @mentioning the role and clicking copy id. https://gyazo.com/765ee645af4db639f6d76034eaa88568

**Comment by Jisagi** [comment]
1. Change your token now that you publicly posted it
2. The bot has to be a member of the newguild, otherwise it will show this error message
3. Adding the Role-Id is not a must. If you are lazy, just name the role `guildcopy`

**Comment by CakeArmy** [comment]
Thanks for the fast response.
I've changed the token. I didn't really think about posting it online since it was a throwaway account anyways.

The bot is a member of the newguild.

Ill try with a role called guildcopy.

**Comment by CakeArmy** [comment]
Still having issues. Not sure what I'm doing wrong. https://gyazo.com/f935aa011e938eea14715ee935263755

**Comment by Jisagi** [comment]
Using guildcopy shoudn't change this anyway, because the newguild id is checked first. It is still strange since this can only happen if the bot isn't member on the new server or the id isn't read correctly from the settings.json but that looks ok, too.
Even if it sounds stupid if i ask this again, but are you really sure the bot which you set the token for in the settings.json is part of the new guild and not just the account the bot is created on?

**Comment by CakeArmy** [comment]
Ah. I see my mistake. I added the bot user to the wrong discord. 
Alright cool. 
Now, if I am trying to copy a discord I don't have admin on, is that possible?

**Comment by Jisagi** [comment]
As long as you don't want to copy bans, you don't need **any** permissions on the original guild at all.
To copy bans you either need `BAN_MEMBERS` or `ADMINISTRATOR`.

**Comment by CakeArmy** [comment]
I saw that, but how do I get the bot user into a discord I don't have admin on?

**Comment by Jisagi** [comment]
You ask the owner(s) but if they don't allow it, you're out of luck since the script only runs on a bot account.

**Comment by CakeArmy** [comment]
Was hoping that wasn't the solution. Anyways, thanks so much.
