### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by PigFanner69** [Jisagi/Discord-guild-copy#131]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.
VVVV

**Additional information:**

- Node.js version:v16.17.0
- Operating system:Windows 10 21H2
![Bild_2022-08-30_235602444](https://user-images.githubusercontent.com/67913438/187550804-0ba8a330-d1ee-4743-acf4-cef66645f2b7.png)
After that just nothing happens

**Comment by Jisagi** [comment]
Everything works as intended. The warnings when installing can be ignored and the output below that shows how you use the script: `node copy.js XXXX`. `XXXX` stands for the possible usages the script offers, like backup, restore or clone and those are explained in the output.
