### ISSUE TITLE
Nothing happened...

### ISSUE THREAD

**Issue by reya1885** [Jisagi/Discord-guild-copy#134]
I am a total noob.  I followed the steps and nothing happened.  What am I doing wrong?  Feel free to e-mail me at burgessfunhouse@gmail.com.  Please help!
[settings.pdf](https://github.com/Jisagi/Discord-guild-copy/files/10047765/settings.pdf)

**Comment by 01NoN** [comment]
same to me here

**Comment by Jisagi** [comment]
The latest version I just pushed should fix most of the current problem. If you still encounter issues, let me know
