### ISSUE TITLE
1.5.17 says error reading permissions and doesn't save to json

### ISSUE THREAD

**Issue by successtheman** [Jisagi/Discord-guild-copy#135]
When running the script on the latest version it outputs this 
```
nodejs: v18.15.0
Language English selected. Translated by Jisagi
Successfully logged in as UserName#1234 Starting script
Latest script version installed
Cannot read properties of undefined (reading 'permissions')
``` 

**Additional information:**

- Node.js version: 18.15.0 LTS
- Operating system: WIn10

**Comment by Jisagi** [comment]
Just to check, did you enable to copy bans? If so, I think I know what it is

**Comment by Jisagi** [comment]
Try the latest version again. Feel free to reopen the issue if it still does not work.

**Comment by successtheman** [comment]
It is fixed on the latest version. Also would you mind taking a look at #132 ? I don't know if you have any interest in adding more features but I still actively use this tool

**Comment by successtheman** [comment]
> Try the latest version again. Feel free to reopen the issue if it still does not work.

@Jisagi It is fixed on the latest version. Also would you mind taking a look at my feature request #132 ? I don't know if you have any interest in adding more features but I still actively use this tool

**Comment by Jisagi** [comment]
The whole emoji backup was a temporary solution from the start, because it doesn't actually backup any images. Same would go for the sticker if it's build the same. I don't know if I can find the time to implemented something decent any time soon though, but maybe in the future.
