### ISSUE TITLE
guildcopy problem

### ISSUE THREAD

**Issue by tovi34** [Jisagi/Discord-guild-copy#14]
hello, i downloaded your guildcopy repository, i put your code on a mismatch bot with the version of node 8.11.2 and the version discord.js 11.3.2, the bot starts ok an error this product has step (7. Creating roles) TypeError: newGuild.roles.create is not a function. I do not understand how to fix this, can you help me please ?

**Comment by Jisagi** [comment]
It works just fine (fresh d.js installation & node 11.4.1). Redownload the latest version of the repostitory and try again.

**Comment by tovi34** [comment]
and when i use your version "discord.js": "git: //github.com/hydrabolt/discord.js.git#master" that puts me an error: TypeError: fn.bind is not a function

**Comment by Jisagi** [comment]
Download the latest repostitory version, you have an outdated one! I just told you that.

**Comment by tovi34** [comment]
ok thanks, can you guide me to this version please?

**Comment by Jisagi** [comment]
Just download the repository and delete your old version?!

**Comment by tovi34** [comment]
ok thanks, i'm doing this right now!

**Comment by tovi34** [comment]
I had already tried this version puts it does not start, it puts a message: Usage:

  * Backup guild to file: node copy.js backup <backupFile (optional)>

  * Restore guild from file: node copy.js restore <backupFile (optional)>

  Clone guild to guild: node copy.js clone

**Comment by tovi34** [comment]
ok but I put (let's Clone = true;) and I still have the message and nothing happens :( excuse me

**Comment by Jisagi** [comment]
Are you not able to read? Use `node copy.js clone` as it tells you.

**Comment by tovi34** [comment]
ok excuse me, thanks
