### ISSUE TITLE
"Undefined" after clone command is run

### ISSUE THREAD

**Issue by EuphoricPenguin** [Jisagi/Discord-guild-copy#15]
Every time I run 
`node copy.js clone`
All I get is `undefined` as a return...

**Comment by shikhir-arora** [comment]
I've just checked it again on a fresh and old install and it works fine. 

Try `sudo node copy.js clone` - and if that doesn't work, please post the full output (minus any sensitive stuff) so we can see the exact undefined error ref.

Typing `node copy.js` should also bring up usage options. 

And verify your Node version is pretty recent; that you've ran npm install and all that and have the proper versions/ `node_modules` -- this should work on Node 8+ but I recommend 9+ or the latest 10, which I use with no issue (10.5.0 with npm 6.1.0).

Undefined can mean a lot, so make sure you've read the guide as @Jisagi did a good job of explaining it :upside_down: - but if you're doing everything properly post the error in detail :)

**Comment by Jisagi** [comment]
Either a) an old version > redownload repository or b) not using a bot token but a user token which will not work.
I did fix the error being undefined in the last commit, at least in the logs if you try to use a user token, guess i should also do this with the console logging.

**Comment by Jisagi** [comment]
@EuphoricPenguin could you resolve the issue?
