### ISSUE TITLE
Requires several Peers

### ISSUE THREAD

**Issue by SuperSaiyanBlue** [Jisagi/Discord-guild-copy#16]
When I run npm install in the directory of the extracted zip, I get the following error:

npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN guildcopy@1.0.1 No repository field.

How do I resolve this?

**Comment by Jisagi** [comment]
That's normal, you can ignore that.

**Comment by SuperSaiyanBlue** [comment]
I assumed it was a problem because I get an error when running copy.js

Script:
C:\Users\Directoryofthescript\copy.js
Line: 1
Char: 1
Error: Syntax error
Code: 800A03EA
Source: Microsoft JScript compilation error

**Comment by SuperSaiyanBlue** [comment]
Additionally, when I run node copy.js, I get:
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Directoryofthescript\copy.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by Jisagi** [comment]
That's not a full stack dump. Check the error logs in the logs folder for the full error log
