### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by Creston1** [Jisagi/Discord-guild-copy#19]
I have installed discord.js using npm install, and not npm install discord.js.

SS: https://i.imgur.com/DrvW1W6.png

**Comment by Jisagi** [comment]
I am on it, give me the time to fix this. Seems to be an update on the api side. I have to see when i get to fixing it.

**Comment by NDAfternoon** [comment]
thanks!

**Comment by NDAfternoon** [comment]
lol was able to kinda fix it
https://imgur.com/a/Ux9HJlZ

**Comment by Jisagi** [comment]
I already know what the problem is but i can't commit it right now since i'm on my phone and i need to update the version check as well which i can't do on mobile either 😉

**Comment by fofoiraq** [comment]
NDAfternoon Can u Help For this I needed to much

**Comment by Jisagi** [comment]
Should be fixed with this commit now https://github.com/Jisagi/Discord-guild-copy/commit/6137f16ad441843daf0356fbd409d37e9a0288ae

**Comment by Jisagi** [comment]
Closing this now. If the problem should still occur, feel free to reopen the issue.
