### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by V4TCH** [Jisagi/Discord-guild-copy#2]
The bot is added to both guilds with the IDs of each in settings.json and the 'guildcopy' role is added on the new server however I still get Error: DiscordAPIError: Missing Permissions. 
<img width="779" alt="screen shot 2018-01-29 at 11 49 11" src="https://user-images.githubusercontent.com/6695600/35509044-93749a02-04ea-11e8-9508-869ce8cfcb22.png">
This is the error I get.
Please help 😄

**Comment by Jisagi** [comment]
Could you enable the debug mode in settings and send the full log with the error please. I want to know at which point this happens.

**Comment by V4TCH** [comment]
Ah, the guildcopy role was not the highest in the new server, moving it to the highest fixed my issue.

Thanks for your quick response!
