### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by bytecooled** [Jisagi/Discord-guild-copy#28]
When I run the npm install command this is what I get
$ npm install
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR!
npm ERR! fatal: unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Craig\AppData\Roaming\npm-cache\_logs\2018-12-01T23_05_09_895Z-debug.log

**Comment by Jisagi** [comment]
This is not related to this script, but a problem with npm. Try (re)installing npm/nodejs or update it.
