### ISSUE TITLE
UnhandledPromiseRejectionWarning: DiscordAPIError: 401: Unauthorized

### ISSUE THREAD

**Issue by Juxstin** [Jisagi/Discord-guild-copy#30]
DiscordAPIError: 401: Unauthorized
    at RequestHandler.execute (C:\Users\Nividia\Desktop\Discord-guild-copy-master\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by Jisagi** [comment]
It would be good to know, when this happens exactly.
The bt might not be able to access the original guild, the new guild or any channel in one of both.

**Comment by Juxstin** [comment]
i have all settings correct: i used node copy.js backup GUILD and it saved, Then after i do the restore gives me that 🤔

**Comment by Jonesyj83** [comment]
Im getting the same error. 
401: Unauthorizes 
Happens when it gets to Deleting channels.
I Deleted everything manually. Then it gets too Setting general data and same error comes up.

**Comment by Jisagi** [comment]
I cannot recreate your issue. Please delete the `node_modules` folder and reisntall everything with `npm install`. The newest version of d.js should work. I know that d.js changed their collection-deletion methods, but I fixed that with v1.0.2 back in august.
If it still doesn't work, upload your guildData.json somewhere like pastebin.com and let me know.

**Comment by Jisagi** [comment]
Since there have not been any further problems since the latest release I will close this issue. Feel free to reopen it, if the problem should persist.
