### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by sweepyoface** [Jisagi/Discord-guild-copy#33]
**Please describe the problem you are having in detail:**

To get this working with Yarn, I had to use [synp](https://github.com/imsnif/synp) to convert yarn.lock to package-lock.json and disable `djsVersionCheck`. Otherwise, it would tell me both Node and discord.js were outdated.

**Additional information:**

- Node.js version: `11.7.0`
- Operating system: `CYGWIN_NT-10.0-WOW`

**Comment by Jisagi** [comment]
I never used yarn before so bare with me. Correct me on this, but can yarn only add direct github dependencies with a certain commit has, since then the `djsVersionCheck` will fail as soon as a single commit is made after creating the `yarn.lock` file.
If `yarn.lock` isn't able to specify the master branch itself, rather than a certain commit, then it will be complicated to update it every time a new commit is made. The same seems to happen with all other dependencies when creating the `yarn.lock` with synp.
If this can be solved, i'd be happy to provide support for yarn.

**Comment by sweepyoface** [comment]
Yarn can depend on the master branch directly.

`yarn add https://github.com/discordjs/discord.js#master`  -->
```
"discord.js@https://github.com/discordjs/discord.js#master":
  version "12.0.0-dev"
  resolved "https://github.com/discordjs/discord.js#ae7269088b99dfff614ea66ba9c67baeb1bd9169"
  dependencies:
    form-data "^2.3.2"
    node-fetch "^2.1.2"
    pako "^1.0.0"
    prism-media amishshah/prism-media
    setimmediate "^1.0.5"
    tweetnacl "^1.0.0"
    ws "^6.0.0"
```

[yarn-lockfile](https://www.npmjs.com/package/yarn-lockfile) could be used to check just like at https://github.com/Jisagi/Discord-guild-copy/blob/master/copy.js#L49

**Comment by Jisagi** [comment]
The problem I mentioned still persists though. When you add a dependency with yarn, it resolves it into the latest commit hash and also only downloads that certain commit state. As soon as a new commit is released, it will not use it. I tried changing the resolved link to an older commit and it did exactly that. So as soon as a yarn.lock exists, it will be outdated eventually.

**Comment by sweepyoface** [comment]
I see the issue here now, and the specific commit resolution is one of the reasons why yarn is used over npm.

What if you checked for the latest version in code via the npm registry or GitHub API based on the commit in `yarn.lock` if it's present? That way either could be used.

**Comment by Jisagi** [comment]
I already use the github api to check for the latest d.js commit hash. That is the source of the "problem". I cannot really determine if someone installed all needed packages via npm or yarn and in the end it doesn't really matter anyway. I keep the script updated for any new d.js commit, so an outdated `yarn.lock` would still result in outdated packages used.
As soon as d.js releases their v12 stable, this is most definitely something I can do though. For now, sadly, I don't see any good solution to support it.

**Comment by sweepyoface** [comment]
I'm not sure I understand, you can't parse `yarn.lock` to get the resolved commit and then compare it to the latest commit via GitHub API?

```
if (resolvedHash !== latestHash || resolvedHash === null) { error! }
```

What's not allowing this?

**Comment by Jisagi** [comment]
I am already doing exactly that [here](https://github.com/Jisagi/Discord-guild-copy/blob/master/copy.js#L49). If one uses yarn to install the packages though, they will not get the latest packages, but exactly the version specified with the commit hash in the `yarn.lock`. And that is the problem when using yarn.
I do get what you mean, at least I think I do. One could in theory differentiate between installations by npm or yarn, but in the end, the script is written and will always be updated for the latest master version. I'm not sure if it would be a good idea to set a fixed commit hash in the yarn.lock till any breaking changes happen in d.js and keep the git-master reference in the package.json. Additionally the script itself would need to differentiate between both as well. So yes, it is possible (to some degree), but it's more work every time d.js to check if the yarn.lock is affected or not.

**Comment by sweepyoface** [comment]
Why would you need to set a fixed hash? Don't commit any lockfile, and simply check the version defined in the `yarn.lock` *generated at install time*?

**Comment by Jisagi** [comment]
Oh lol, I totally misunderstood how yarn works then. Don't ask me why, but I somehow assumed yarns lockfile is equivalent to the package.json and not npms lockfile. Well, seems like I've talking bs the whole time then, sorry :D.
I will close you PR (later) and do it in the next few days. I already have an idea, w/o being forced to add new translations. I hope that's fine with you. I'll might use some of your code as well, not sure about the yarn.lock library though.

**Comment by Jisagi** [comment]
I had to use another library. Yarn made their own official one for parsing their lockfile and I had problems with the one you used in your PR. Yarn should work just fine now.
Sorry for the hassle, I was just blind to see how yarn actually works.

**Comment by sweepyoface** [comment]
No problem, thanks!
