### ISSUE TITLE
Copy bots

### ISSUE THREAD

**Issue by WilsontheWolf** [Jisagi/Discord-guild-copy#34]
This is a suggestion and I am not sure if it's even possible. I was wondering if it would reinvite all bots it could. The invite if of the hot for the URL is the bots id so it could fetch it. If this is possible it would be comvient.

**Comment by Jisagi** [comment]
Sadly, it's not possible. You can automatically create the (bot)invite, but only a human can authorize a bot to join a guild. Circumventing and automating a google captcha isn't something I want to add. Sorry

**Comment by WilsontheWolf** [comment]
Ok. What if it just sent all the invite links when it's done copying into a text channel?

**Comment by Jisagi** [comment]
I will take a look into it, seems like a nice addition. I am not sure when I got the time for it though.

**Comment by Jisagi** [comment]
Latest Version v1.2.1 now posts invitelinks for all bots which are member of the original guild. This only works, if the bot is (still) a member of the original guild. The feature is automatically disabled if this is not the case.
Thanks for the nice idea :+1:
