### ISSUE TITLE
Nodejs version to 8.0.0 or higher

### ISSUE THREAD

**Issue by Huslyx1** [Jisagi/Discord-guild-copy#36]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:** It keeps putting out "Please update your Nodejs version to 8.0.0 or higher" even though i upgraded the node.js please help

- Node.js version: v10.15.1
- Operating system: Windows 10

**Comment by Jisagi** [comment]
This error shows up when no `package-lock.json` file is present. It was introduced with npm 5.0 which was bundled with nodejs 8.0.0 back then. Your nodejs version might be new enough, but your npm might not be. You can check it's version by running `npm -v` in the console and update it with `npm i -g npm`.

**Comment by Huslyx1** [comment]
Erm, okay i thought i updated that already but ill give it a shot.

**Comment by Huslyx1** [comment]
Okay, i did what you said. and its still saying the message.

npm -v
6.8.0

node -v
v10.15.1

**Comment by Jisagi** [comment]
Is there a file called `package-lock.json` in the directory? Did you run `npm install` at least once after downloading the repository?

**Comment by Huslyx1** [comment]
there isnt a file called packpage-lock.json and i did do the npm install

**Comment by Jisagi** [comment]
Ok, that is indeed strange. Delete the `node_modules` folder and rerun `npm install`. If it still doesn't create a `package-lock.json` file, then it might a problem with npm at this point.

**Comment by Huslyx1** [comment]
Uh, i dont see a node-modules even though i did npm install

**Comment by Jisagi** [comment]
Try to run `npm config set package-lock true`. Maybe you or another program deactivated it at some point

**Comment by Huslyx1** [comment]
Okay, still the same, nothing changed

**Comment by Jisagi** [comment]
Might as well reinstall ndoejs at this point. I have no clue what else than a messed up npm config it could be. It's most definitely not a script issue though.

**Comment by Huslyx1** [comment]
ive tried that reinstall for node.js..

**Comment by Jisagi** [comment]
Then I'm out of ideas. In the end, it's not script related and I can't help you more then I already did.

**Comment by Huslyx1** [comment]
i redid what you said and got this error? 

"C:\Users\Home\Desktop\Discord-guild-copy-master>npm install
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2019-02-19T22_00_56_340Z-debug.log

C:\Users\Home\Desktop\Discord-guild-copy-master>"

**Comment by Jisagi** [comment]
Sounds like git is missing now. Install it manually from [here](https://git-scm.com/download/win)

**Comment by roxer1993** [comment]
get the same errror, on unbuntu 18.04. npm install gives the following:
├── UNMET PEER DEPENDENCY @discordjs/uws@^11.149.1
├── UNMET PEER DEPENDENCY bufferutil@^4.0.1
├─┬ discord.js@12.0.0-dev  (git://github.com/hydrabolt/discord.js.git#1207c243d1d819b2a78230bb194e07f14d966ea9)
│ ├── UNMET PEER DEPENDENCY ffmpeg-binaries@^4.0.0
│ ├── UNMET PEER DEPENDENCY ffmpeg-static@^2.4.0
│ ├─┬ form-data@2.3.3
│ │ └── asynckit@0.4.0
│ ├── node-fetch@2.3.0
│ ├── UNMET PEER DEPENDENCY node-opus@^0.3.1
│ ├── UNMET PEER DEPENDENCY opusscript@^0.0.6
│ ├── pako@1.0.10
│ ├── prism-media@1.0.1
│ ├── setimmediate@1.0.5
│ ├── tweetnacl@1.0.1
│ └─┬ ws@6.1.4
│   └── async-limiter@1.0.0
├── UNMET PEER DEPENDENCY erlpack@discordapp/erlpack
├── UNMET PEER DEPENDENCY libsodium-wrappers@^0.7.4
├─┬ request@2.88.0
│ ├── aws-sign2@0.7.0
│ ├── aws4@1.8.0
│ ├── caseless@0.12.0
│ ├─┬ combined-stream@1.0.7
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.2
│ ├── forever-agent@0.6.1
│ ├─┬ har-validator@5.1.3
│ │ ├─┬ ajv@6.10.0
│ │ │ ├── fast-deep-equal@2.0.1
│ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ ├── json-schema-traverse@0.4.1
│ │ │ └─┬ uri-js@4.2.2
│ │ │   └── punycode@2.1.1
│ │ └── har-schema@2.0.0
│ ├─┬ http-signature@1.2.0
│ │ ├── assert-plus@1.0.0
│ │ ├─┬ jsprim@1.4.1
│ │ │ ├── extsprintf@1.3.0
│ │ │ ├── json-schema@0.2.3
│ │ │ └─┬ verror@1.10.0
│ │ │   └── core-util-is@1.0.2
│ │ └─┬ sshpk@1.16.1
│ │   ├── asn1@0.2.4
│ │   ├─┬ bcrypt-pbkdf@1.0.2
│ │   │ └── tweetnacl@0.14.5
│ │   ├── dashdash@1.14.1
│ │   ├── ecc-jsbn@0.1.2
│ │   ├── getpass@0.1.7
│ │   ├── jsbn@0.1.1
│ │   ├── safer-buffer@2.1.2
│ │   └── tweetnacl@0.14.5
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.22
│ │ └── mime-db@1.38.0
│ ├── oauth-sign@0.9.0
│ ├── performance-now@2.1.0
│ ├── qs@6.5.2
│ ├── safe-buffer@5.1.2
│ ├─┬ tough-cookie@2.4.3
│ │ ├── psl@1.1.31
│ │ └── punycode@1.4.1
│ ├── tunnel-agent@0.6.0
│ └── uuid@3.3.2
├── UNMET PEER DEPENDENCY sodium@^3.0.2
└── UNMET PEER DEPENDENCY zlib-sync@^0.1.4

npm WARN discord.js@12.0.0-dev requires a peer of @discordjs/uws@^11.149.1 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.4 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^3.0.2 but none was installed.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.4 but none was installed.
npm WARN prism-media@1.0.1 requires a peer of ffmpeg-binaries@^4.0.0 but none was installed.
npm WARN prism-media@1.0.1 requires a peer of ffmpeg-static@^2.4.0 but none was installed.
npm WARN prism-media@1.0.1 requires a peer of node-opus@^0.3.1 but none was installed.
npm WARN prism-media@1.0.1 requires a peer of opusscript@^0.0.6 but none was installed.
npm WARN guildcopy@1.2.1 No repository field.

Can that be the issue?

**Comment by Jisagi** [comment]
Check if npm is up-to-date and delete the `node_modules` folder and `package-lock.json`. Those are the usual culprits. The warning at the end can be ignored, those are library related and only a notice if you need voice feature or other stuff.

**Comment by roxer1993** [comment]
deleted all, redownloaded from git and worked perfecly, thanks alot for this code :D

**Comment by Jisagi** [comment]
Since there haven't been any new posts by the original creator of the issue, I'll close this. If it's still not fixed, do not hesitate to reopen it.
