### ISSUE TITLE
Outdated script version?

### ISSUE THREAD

**Issue by Zeridiant** [Jisagi/Discord-guild-copy#37]
**Please describe the problem you are having in detail:**

I executed the script and heres what I got:

Language English selected. Translated by Jisagi
Successfully logged in as Discord Guild Cloner#6821. Starting script
Latest discord.js version installed
You are not using the latest script version. Please redownload the newest version.
Your version: 1.2.0
Latest version: 1.2.1

How do I download the newest version?

**Additional information:**

- Node.js version: 10.15.1
- Operating system: Windows 10

**Comment by Jisagi** [comment]
Just redownload the repository from github and delete your current folder.

**Comment by Jisagi** [comment]
No wait, I fucked up here. Gimme a sec to fix it.

**Comment by Zeridiant** [comment]
Thank you!
