### ISSUE TITLE
NewGuildAdminRole.permissions.has is not a function

### ISSUE THREAD

**Issue by CeruleanFlare** [Jisagi/Discord-guild-copy#39]
when I run node copy.js clone
I get this:
Language English selected. Translated by Jisagi
Successfully logged in as PalBot#1690. Starting script
Latest script version installed
newGuildAdminRole.permissions.has is not a function

I just did npm install and also I have input a role ID into the settings.

**Comment by CeruleanFlare** [comment]
I also made sure that the role has admin

**Comment by CeruleanFlare** [comment]
ok i fixed it by deleting a line in the validator.js

**Comment by Jisagi** [comment]
Just randomly deleting files does NOT help solving the problem. You don't seem the have the latest version of discord.js installed. Do **not** install any npm package, but only run `npm install`. Deleting the `validator.js` just skips the check.
Redownload the latest script version and re-run `npm install` and then try again.

**Comment by Jisagi** [comment]
I will be closing this issue, since there haven't been any new problems. If you still need help, feel free to reopen it.
