### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by champagneGIT** [Jisagi/Discord-guild-copy#42]
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit

I receive that error message everytime i run node copy.js clone

**Comment by Jisagi** [comment]
You might want to update your node.js version.
Also, do you run the script standalone, or inside a bot. It complains about too many listeners. The script itself only uses a single one, so it's the environment it's running in, or nodes missing Eventemitter which needs node v10 or newer.

**Comment by Jisagi** [comment]
Closing this now. If the error persists, feel free to reopen the issue.
