### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by iAuvic** [Jisagi/Discord-guild-copy#43]
**Please describe the problem you are having in detail:**
Error when the bot try to delete something

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.
DiscordAPIError: 401: Unauthorized
    at RequestHandler.execute (C:\Users\Auvic\Desktop\Newp\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Additional information:**

- Node.js version: Last Version.
- Operating system: Win 10 x64

**Comment by Jisagi** [comment]
Make sure the Bot has a role with Administrator permissions. This role also needs to be *at the top* of the role list. Usually the script would complain about those things, but I can't think of anything else right now. If this doesn't work, upload or post the full log from the log folder in here. Without knowing where exactly it fails, makes it harder to guess what the problem might be.

**Comment by iAuvic** [comment]
https://paste.ubuntu.com/p/syCK8wJjxd/

(I'm using my user token.)

**Comment by Jisagi** [comment]
Using a user token would be the problem then. The script should exit when using one and it does that for a reason. The discord.js library doesn't support user tokens anymore and therefore they will not work. Neither with my script or the discord.js library in general.

**Comment by iAuvic** [comment]
Yes, the user key is the problem, i used an bot token now and worked, i'll copy the guildData with my token and use the bot to restore it, should solve. xD
