### ISSUE TITLE
newGuildAdminRole.permissions.has is not a function

### ISSUE THREAD

**Issue by Samdzgt** [Jisagi/Discord-guild-copy#44]
Bonsoir, j'ai trouvé votre Discord-guild-copy, en cherchant une version de Xénon en javascript.
Je l'ai téléchargé, extraire, puis fait les settings et je l'ai 'node copy.js clone'.
Problème, il me dit que "newGuildAdminRole.permissions.has is not a function", je cherche la solution pour y remédier sur internet, ainsi que dans les issues, et on voit qu'il faut avoir la version de nodejs > 12.x.x.
J'ai donc fait la mise à jour, mais le problème est toujours présent.
Je recherche d’avantage sans réponse à mon problème.
Avez-vous une solution ?

J'ai même mit la ligne concernant cette erreur dans le validator en commentaire pour voir la suite, mais cette fois-ci, c'est "guild.iconURL is not a function" qui s'y met.
J'ai même mit aussi la ligne qui vérifie la version de discord.js (qui est à la dernière version mais me dit qu'il faut la retélécharger sans-cesse) en commentaire.

J'apprécie si vous avez la solution.
Si je dois vous ajouter sur discord ?

Bonne soirée, et merci pour ce guild-copy.
-----------------------------------------------------
Good evening, I found for Discord-guild-copy, looking for a version of Xenon in js.
I downloaded it, extracted it, then made the settings and I got it 'node copy.js clone'.
Problem, he tells me that "newGuildAdminRole.permissions.has is not a function", I seek the solution to fix it on the internet, as well as in issues, and we see that we must have the version of nodejs> 12.x.x.
So I did the update, but the problem is still present.
I am looking for more unanswered to my problem.
Do you have a solution ?

I even put the line concerning this error in the validator in comment to see the continuation, but this time, it is "guild.iconURL is not a function" which is put there.
I even put also the line which verifies the version of discord.js (which is the last version but tells me that it must be reloaded again and again) in comment.

I appreciate if you have the solution.
If I have to add you on discord?

Good evening, and thank you for this guild-copy. 
(I have use google translate for this. Sorry).

**Comment by Jisagi** [comment]
> I even put also the line which verifies the version of discord.js (which is the last version but tells me that it must be reloaded again and again) in comment.
This does sound like, you did not install discord.js correctly. You do not have to install it manually, but only run `npm install` after downloading the script. Afterwards, you can already run the clone command `node copy.js clone`. The two erros you got with permissions and iconurl seem to confirm this, since those properties are handled/stored somewhere else in the stable version of discord.js.
Deleting the `node_modules` folder and the `package-lock.json` file and running `npm install` should fix this.

**Comment by Samdzgt** [comment]
Merci d'avoir, répondu.
Je viens de supprimer le "node_modules" et le "package-lock.json", puis lancer un "npm install".
Dont voici le résultat du "npm install"
`npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN discord.js@11.5.0 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN guildcopy@1.3.1 No repository field.`

Puis un "node copy.js clone".
`*node copy.js clone*
Language English selected. Translated by Jisagi
Successfully logged in as Peut-M'Importe#6291. Starting script
You don't have the latest version of discord.js installed. Please delete the 'node_modules' folder and the 'package-lock.json'/'yarn.lock' and run 'npm install'/'yarn install' again`
J'ai ré-supprimé le fichier "node_modes", ainsi que le fichier "package-lock.json", mais cela fait donne toujours la même erreur.

----------------------------

Thank you for answering.
I just removed the "node_modules" and the "package-lock.json", then run an "npm install".
Which is the result of the "npm install"
`npm deprecated WARN snekfetch@3.6.4: use node-fetch instead
npm record created at lockfile as package-lock.json. You should commit this file.
npm WARN discord.js@11.5.0 requires a peer of bufferutil@i4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of erlpack @ discordapp / erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of libsodium-wrappers@*0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of node-opus@i-0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of opusscript@i-0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of sodium@i2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of @ discordjs / uws @ ^ 10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN guildcopy@1.3.1 No repository field.`

Then a "node copy.js clone".
`* node copy.js clone *
Language English selected. Translated by Jisagi
Successfully logged in as Can Mistress # 6291. Starting script
You do not have the latest version of discord.js installed. Please delete the 'node_modules' folder and the 'package-lock.json' / 'yarn.lock' and run 'npm install' / 'yarn install' again`
I re-deleted the "node_modes" file, as well as the "package-lock.json" file, but that still gives the same error.

**Comment by Jisagi** [comment]
The first few errors from npm install can be ignored.
The error thrown by the clone command though confirm what I was thinking. Why it persists after reinstalling the correct version is strange though.
My guess is, that you maybe installed discord.js globally and it's using that (outdated) version. You can check by going into the global packages folder `C:\Users\<USERNAME>\AppData\Roaming\npm\node_modules` and check if there is a folder called `discord.js`. If so, delete it and rerun the script. If this still doesn't solve the issue. Redownload the whole script itself, run npm install again and then try to run the clone command.

**Comment by Samdzgt** [comment]
D'accord, merci d'avoir répondu.
Je vais regarder dans mes appdata, et vous dire quoi.
En effet, est-ce étrange ? Le dossier est totalement vide.

------------
Okay, thank you for responding.
I will look in my apps, and tell you what.
Indeed, is it strange? The folder is totally empty.
![Capture](https://user-images.githubusercontent.com/45718118/58169170-64376e80-7c90-11e9-8467-52a5fe92eab5.PNG)

**Comment by Jisagi** [comment]
The folder being empty is good. This means it is using the version installed inside the `node_modules` in the scripts folder. So do not worry about that. If might have been a problem if there was something in it.

**Comment by Samdzgt** [comment]
Que dois-je faire dans ce cas là ? Même en supprimant le dossier et le fichier, le problème est toujours présent.
What should I do in this case? Even removing the folder and file, the problem is still present.

**Comment by Jisagi** [comment]
Did you try redownloading the whole script yet?

**Comment by Samdzgt** [comment]
Comment ça ?
Retélécharger le guild-copy ? 

What do you mean ?
Redownloading the guild-copy?

**Comment by Jisagi** [comment]
Yes, redownload the whole script from github and delete what you downloaded so far. There really is something broken with it as it seems.

**Comment by Samdzgt** [comment]
Je vais aller le retélécharger, et supprimer les "anciennes" version présentes sur mon pc.
Voilà, j'ai mis en place les ids, et le token du bot.
Je fais un 'npm install' ?

**Comment by Jisagi** [comment]
Yes, delete all the old files, redownload everything, fill in the token and the necessary ids and run `npm install` and tehn `node copy.js clone`

**Comment by Samdzgt** [comment]
Ok. Après le "npm install".
`npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\USER\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\USER\package.json'
npm WARN discord.js@11.5.0 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.0 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.`
Puis le "node copy.js clone".
` Cannot find module '@yarnpkg/lockfile'`
Il n'a pas installé les modules.

**Comment by Jisagi** [comment]
you have to run `npm install` inside the extracted script folder, otherwise it will not install everything correctly.
Also, can you run `npm -v` and tell me, what version you are running? It should be something along v6.x.x

**Comment by Samdzgt** [comment]
Version : 6.9.0
Oui, j'ai exécuté le "npm install" à la racine du discord-guild-copy.

**Comment by Jisagi** [comment]
Try running `npm init`, then `npm install` and then the clone command

**Comment by Samdzgt** [comment]
Yes.

**Comment by Samdzgt** [comment]
`npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:`

**Comment by Jisagi** [comment]
npm tries to use git to install discord.js, but git does not seem to be installed. please install it from here https://git-scm.com/downloads

**Comment by Samdzgt** [comment]
Ok thanks. I go download it and installed it

**Comment by Samdzgt** [comment]
J'ai fini d'installer git, j'exécute le "npm init", puis le "npm install".
`npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

**Comment by Jisagi** [comment]
What happens when you run `git` in the console. Does it display a help text or something like "command not found"?

**Comment by Samdzgt** [comment]
`git : Le terme «git» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme
exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct
et réessayez.
Au caractère Ligne:1 : 1
+ git
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by Samdzgt** [comment]
Big thanks

**Comment by Jisagi** [comment]
Glad to help 👍

**Comment by Samdzgt** [comment]
I close this issues. Thanks 👍

**Comment by iraouf** [comment]
hey, im having this exact same issue

**Comment by iraouf** [comment]
Language English selected. Translated by Jisagi
Successfully logged in as Testing something ;)#5871. Starting script
You don't have the latest version of discord.js installed. Please delete the 'node_modules' folder and the 'package-lock.json'/'yarn.lock' and run 'npm install'/'yarn install' again

**Comment by Jisagi** [comment]
> You don't have the latest version of discord.js installed. Please delete the 'node_modules' folder and the 'package-lock.json'/'yarn.lock' and run 'npm install'/'yarn install' again

Do what is tells you :)
And please open a new issue next time instead of posting in different one

**Comment by iraouf** [comment]
I did what it told me

**Comment by iraouf** [comment]
have been trying everything for an hour, also what was said in this thread

**Comment by iraouf** [comment]
also tried reinstalling the directory

**Comment by Jisagi** [comment]
No you obviously did not and as I saiud before, please open a new issue
