### ISSUE TITLE
Discord nitro extra emoji space...

### ISSUE THREAD

**Issue by Bartixxx32** [Jisagi/Discord-guild-copy#46]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

Hello i found the problem in script. If server has nitro boost and like extra 50+ emoji space if want to use script to clone discord server to other server it will hang up and freeze when space will end (as my observation) The solution can be. If it have any error when creating emoji, skip this and go next step :)

**Additional information:**

- Node.js version: 10
- Operating system: ubuntu

**Comment by Jisagi** [comment]
Yea, I was too lazy to fix that yet :sweat_smile: 
I will probably push a PATCH version today or tomorrow to include everything nitro boost related. I need to check what else there is to keep in mind, like new voice bitrates and such. Thanks for the heads up

**Comment by Jisagi** [comment]
Update: I'll be waiting for [this](https://github.com/discordjs/discord.js/pull/3364) to push a patch, then everything will be comlplete in one commit. They seem to have forgotten to add a way to set the guild banner.
