### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Yeahhahaha** [Jisagi/Discord-guild-copy#51]
Latest discord.js version installed
Latest script version installed
1. Serializing general data
2. Serializing role data
Cannot read property 'id' of undefined

it gets to the second stage and just gives that error

Edit: 
It's this bit of code in serializer.js

    static serializeRoles(guildToCopy) {
        let roleCol = guildToCopy.roles.sort((a, b) => b.position - a.position);
        let roles = roleCol.map(role => {
            return {
                idOld: role.id,
                name: role.name,
                hexColor: role.hexColor,
                hoist: role.hoist,
                mentionable: role.mentionable,
                position: role.position,
                rawPosition: role.rawPosition,
                defaultRole: guildToCopy.defaultRole.id === role.id,
                permBitfield: role.permissions.bitfield,
            };
        });

**Comment by Jisagi** [comment]
Fixed in my latest commit. discord.js changed their reference for the @everyone role.
