### ISSUE TITLE
"You are not running the latest version of discord.js"

### ISSUE THREAD

**Issue by AnyGiv3nDay** [Jisagi/Discord-guild-copy#52]
so i recently lost control of my discord account but my friend was a owner as well as me (we shared equal perms) so i made my bot all that shizzle shazzle but finally i had to edit package.json to the latest version of discord.js because it was giving me errors (from the npm website itself) so i'm actually running discord.js = 11.5.1 which is currently the latest version to my knowledge any help would be greatly appreciated thanks in advance 
Edit: All i really need to know is what version of discord.js this cloner runs on

**Comment by AnyGiv3nDay** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/16693909/63633957-10814c00-c616-11e9-8d1b-e7950ce25b85.png)
just wanted to add  this

**Comment by Jisagi** [comment]
Please do not install any release versions. Read the installation guide again. It clearly states, you should just run `npm install` to get the latest version from github, not the latest release version. You neither need nor should edit anything inside the `package.json` at all.

**Comment by AnyGiv3nDay** [comment]
that doesn't help me because i get errors when i run "just npm install without editing" and this is what i got
![Screenshot_4](https://user-images.githubusercontent.com/16693909/63637211-af6e6e00-c63f-11e9-9df8-c88cd77307a8.png)

**Comment by Jisagi** [comment]
That sounds like you don't have git installed on your machine. Just running something else and expecting it to work won't help you either.
Here is git for windows https://git-scm.com/download/win

**Comment by AnyGiv3nDay** [comment]
ok thanks i appreciate it
