### ISSUE TITLE
Node Version Issue...

### ISSUE THREAD

**Issue by GetRektOrElse** [Jisagi/Discord-guild-copy#53]
When I run node copy.js clone it gives me an error of "Please update your Nodejs version to 10.0.0 or higher" even though I have node v10.16.3

What do I do?
![Capture](https://user-images.githubusercontent.com/41167684/64057599-7153db80-cb64-11e9-949b-47d1e0ae6363.PNG)

- Node.js version: v10.16.3
- Operating system: Windows 10

**Comment by Jisagi** [comment]
Haha, I didn't expect this to happen tbh. The error doesn't actually check the node version itself, but is triggered when there is neither a `package-lock.json` nor a `yarn.lock` file present. Make sure those exist. When installed with npm, the first one should be present, if you didn't delete it manually.
I'll should probably change the error message text as well ;D

**Comment by GetRektOrElse** [comment]
Thanks, I'm kinda an idiot.... :D

**Comment by GetRektOrElse** [comment]
It is still not working after I downloaded yarn and the package lock...

Do you have discord so I can DM you there?

**Comment by Jisagi** [comment]
Jisagi#0230
