### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Red09discord** [Jisagi/Discord-guild-copy#57]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.
 
![image](https://user-images.githubusercontent.com/54461947/65831920-0d940e00-e2dc-11e9-9450-91c5865789a8.png)
what do i do? it's not cloning and its a bot token
**Additional information:**

- Node.js version:
- Operating system: windows 7

**Comment by Jisagi** [comment]
Looks like your nodejs version is so old, it doesn't even know async iteration. Update nodejs to at least 10.x.x, though 12.x.x is preferable

**Comment by Red09discord** [comment]
Will the issue be solved if I update my nodejs?

**Comment by Jisagi** [comment]
Update nodejs and try, asking if it solves it, won't solve it for sure.

**Comment by Red09discord** [comment]
Ok, ill post a ss after updating if any error arises, thanks!

**Comment by Red09discord** [comment]
![image](https://user-images.githubusercontent.com/54461947/65832540-ccebc300-e2e2-11e9-9d9a-71db0c02dd09.png)
um?

**Comment by Jisagi** [comment]
Read what it says again, it's self explanatory

**Comment by Red09discord** [comment]
so, it means that copy.js now has the cloned server?

**Comment by Jisagi** [comment]
No, it didn't do anything yet. Read what the script tells you how to use it

**Comment by Red09discord** [comment]
ok so i should type node copy.js backup?

**Comment by Red09discord** [comment]
ok, it's asking to update... did u post an update?

**Comment by Red09discord** [comment]
fml

**Comment by Jisagi** [comment]
No, I did not, at least not in the last 2 weeks

**Comment by Red09discord** [comment]
lmfao i downloaded this 2 months ago

**Comment by Red09discord** [comment]
btw, This guy named y21 on github has made a script that allows you to copy a server with a user token thats also based on js XD it saves the copied guild in a notepad file and u have to use another program made by him to build the server it's op but the thing is it does not copy perms, channels not in correct category etc.,

**Comment by Jisagi** [comment]
As I already said before. If he uses d.js as library his script is using an version which still supports user tokens. This version is NOT able to backup everything my script does. That is the sole reason why I'm not using said version to begin with. The dropped user token supprot never bothered me, so I never really cared.

**Comment by Red09discord** [comment]
yeah the cloner is working now thanks so much!

**Comment by Jisagi** [comment]
no problem :+1:

**Comment by Red09discord** [comment]
> As I already said before. If he uses d.js as library his script is using an (old) version which still supports user tokens. This version is NOT able to backup everything my script does. That is the sole reason why I'm not using said version to begin with. The dropped user token supprot never bothered me, so I never really cared.

ok thanks anyways!

**Comment by y21** [comment]
Hello, maintainer of the mentioned project here. I made `serverbuild`, an open source project that allows cloning guilds, similar to this repository a while ago. In 2017, which was when I initially started working on it, there were no categories and I forgot about permission overrides. 
@Jisagi is right, it depends on what version you are using. 
Discord.js master (which is what this repository uses) no longer supports user tokens and you should not be using them anyways, since that is against Discords Terms of Services.
Discord.js stable still supports them. However, at some point, master will be merged into stable and user tokens won't be supported anymore.

**Comment by Red09discord** [comment]
What about cloners made in python?

**Comment by y21** [comment]
If the only thing you need here is being able to login as a regular user account, why don't you just modify library files? There is a check somewhere in Discord.js' source code that prevents you from logging in as a user account, so simply removing it should allow it. 
Alternatively, use a bot account if possible?

**Comment by Red09discord** [comment]
What how
