### ISSUE TITLE
Help again sorry

### ISSUE THREAD

**Issue by Red09discord** [Jisagi/Discord-guild-copy#58]
**Please describe the problem you are having in detail:**
![image](https://user-images.githubusercontent.com/54461947/65877579-a9d81680-e3a9-11e9-905b-0144444a985f.png)
what do i do?
Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:**

- Node.js version:latest
- Operating system:win-7

**Comment by Jisagi** [comment]
Don't use yarn, if you already used `npm install`. You CAN use yarn, but npm is the program of choice and since it's bundled with node, nothing needs to be installed additionally compared to yarn.

**Comment by Red09discord** [comment]
The above error was for non not yarn

**Comment by Jisagi** [comment]
Oh true, missed that. Looks like git is not installed. You can download it here for windows https://git-scm.com/download/win (the download starts automatically)

**Comment by Red09discord** [comment]
ok
