### ISSUE TITLE
Adaptation request

### ISSUE THREAD

**Issue by Dany-LF** [Jisagi/Discord-guild-copy#61]
Is it possible to adapt it for discord.js 11.5.1?

**Comment by Jisagi** [comment]
Last time I checked the v11 branch was 11.2.x which wasn't able to provide what I needed. v11.5.x might do that, but to be honest, I will not adapt it even if it's possible. Either it works out of the box with v11 or not. I won't maintain two seperate versions and I don't see any advantages in v11 anyway, beside the fact that v12 is not stable (yet).

**Comment by Dany-LF** [comment]
You wouldn't have to maintain both versions just the one of v12 but it would be easier to adapt this once to v11.5.1
