### ISSUE TITLE
Issue when running npm install

### ISSUE THREAD

**Issue by Grim5603** [Jisagi/Discord-guild-copy#63]
**Please describe the problem you are having in detail:**

when running npm install:

npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
**Additional information:**

- Node.js version: 13.1.0
- Operating system: win10

**Comment by Grim5603** [comment]
nevermind, i fixed this by editing the package file.

**Comment by kyesuwu** [comment]
I am having the same problem how can this be fixed ?

**Comment by Jisagi** [comment]
Install [git for windows](https://gitforwindows.org/) and try again. A reboot might be needed after git installation

**Comment by kyesuwu** [comment]
oh i'm so dumb, sorry and thanks for replying
