### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ploural** [Jisagi/Discord-guild-copy#65]
https://pastebin.com/xha7wg7E

**Additional information:**

- Node.js version: v10.16.3
- Operating system: Windows 10 64x

**Comment by Jisagi** [comment]
Sounds like you're missing git on your machine. Try installing https://gitforwindows.org/ and then try again. (A restart might be needed after git installation)

**Comment by ploural** [comment]
Yea, i didnt installed git, now ive copied my server. And your script is
the best

Jisagi <notifications@github.com> schrieb am So., 26. Jan. 2020, 12:09:

**Comment by ploural** [comment]
I saw that you are german, can we talk on Teamspeak or Discord?
My discord Name: Ploural#0001


2changes <sugiokyochu@gmail.com> schrieb am So., 26. Jan. 2020, 18:55:
