### ISSUE TITLE
Error While running

### ISSUE THREAD

**Issue by megamasso** [Jisagi/Discord-guild-copy#68]
C:\Users\Desktop\Discord-guild-copy-master>node copy.js clone
nodejs: v10.19.0
Language English selected. Translated by Jisagi
Successfully logged in as Artyom#7661. Starting script
Latest discord.js version installed
Latest script version installed
client.guilds.has is not a function

**Comment by Jisagi** [comment]
d.js completely removed datastores, so I need to change everything to the new managers. I am on it and push a commit when I'm done.
