### ISSUE TITLE
Contact me on discord

### ISSUE THREAD

**Issue by wbscrims** [Jisagi/Discord-guild-copy#74]
Hi there, please contact me Ackticql#1277 to discuss

**Comment by Jisagi** [comment]
What is there, that cannot be discussed here?

**Comment by wbscrims** [comment]
Sorry, I just thought that it would be easier to talk there. I'm hosting the bot via Heroku and when I try to create a backup file for the server, it doesn't actually do anything.

**Comment by Jisagi** [comment]
That is indeed not much. Question is though, nothing doesn't really help debugging it. If nodejs doesn't even run, it does sound like a node problem. Might want to (re)install the latest version (again). Otherwise open the `settings.json` and check if `output` is set to `all`.
