### ISSUE TITLE
Gave me an error

### ISSUE THREAD

**Issue by pizzagirl1228** [Jisagi/Discord-guild-copy#77]
**So I am probably being stupid but I dont quite understand everything here.
This is what happened when I installed the file, unzipped, edited settings and ran npm install:**
`PS C:\Users\marie\OneDrive\Documents\Coding\Discord-guild-copy-master> npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marie\AppData\Roaming\npm-cache\_logs\2020-05-19T19_35_51_799Z-debug.log`

**Additional information:**
I did all of the required steps, made a bot, etc. 

- Node.js version: 12.16.3
- Operating system: windows 10 x64

**Comment by Jisagi** [comment]
I should really add this to the README at some point. Install [git for windows](https://gitforwindows.org/) and try again. A reboot might be needed after git installation

**Comment by pizzagirl1228** [comment]
Oh I am so sorry. I will do that. Yeah so I am a total noob lmaooo. TYSM for replying so early!!!

**Comment by Jisagi** [comment]
Nothing wrong being a beginner, this is a fairly common "issue"

**Comment by pizzagirl1228** [comment]
That fixed it! Thanks so much, this project is super cool & helped me understand js a tiny bit better ty :)
