### ISSUE TITLE
Would it be possible to allow importing/exporting bans only?

### ISSUE THREAD

**Issue by rjmxtechnology** [Jisagi/Discord-guild-copy#81]
Say I have a server with people already banned but I also want to add some other bans from a backup, being able to import the bans from the backup and keep the existing ones would be very helpful

Not sure if the API prevents this or if it actually may be possible to do. At the least I guess you could have it iterate through a ban list and then import the bans that way

**Comment by Jisagi** [comment]
With the current script, no. I could add a setting for everything else though, so it can be toggled off like emojis and bans. I probably have some time to implement that next weekend.

**Comment by rjmxtechnology** [comment]
Sweet!! If you can do that it would be an amazing feature. I don't really know of any other scripts such as this one which are within TOS (not using user token etc...) so this is really the only viable option imo. Being able to toggle which settings to import/export would be awesome.

Just to clarify this would allow you to import bans to a server that already exists from a backup? This is my intention

**Comment by Jisagi** [comment]
Check out the latest version. Now you can toggle the guild cleanup and everything else except bans. The README explains how to toggle which part.
