### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Zinibow** [Jisagi/Discord-guild-copy#82]
I need help, idfk what I am doing, please add me on Discord, ! Sophie#6969 (538604507064696832)

**Comment by Jisagi** [comment]
There issue tracker here exists for a good reason, the readme as well. Not knowing what you do, is not something I can help you with. You need at least something you want to do with the script and then the error you get when executing it. If you can't even reach this part, it's probably not for you

**Comment by GamerZ6154** [comment]
How to run it?
whats the run cmd?

**Comment by Jisagi** [comment]
Everything is explained in teh README. Please actually read it, then you will find all needed commands

**Comment by Zinibow** [comment]
My Discord is ! Ally#6969, please add me Jisagi

**Comment by Jisagi** [comment]
I will close this now. Please use the issue tracker here on github. I will not provide direct help on discord. Feel free to reopen it, if you want to actually accept the help I'm offering here.
