### ISSUE TITLE
Missing Permissions issue?

### ISSUE THREAD

**Issue by hithereimxplicit** [Jisagi/Discord-guild-copy#84]
Having a missing permissions issue, both roles have admin.
![image](https://user-images.githubusercontent.com/73083704/98017782-b8270c00-1dcd-11eb-9b4e-d686d1cf2c78.png)

**Comment by Jisagi** [comment]
Well obviously you don't have enough permissions. You opened another issue where you didn't want the guildcopy role to be at the top and now you get this error because the guildcopy role is not at the top. There is a reason this checks is done.

**Comment by hithereimxplicit** [comment]
My ownership account was terminated therefore I can't put the bot role at the top, can I bypass this requirement somehow?

**Comment by Jisagi** [comment]
No, you can't.

**Comment by hithereimxplicit** [comment]
Why not? There should be a way to disable this feature. The reason I'm using this script is because Xenon and XtraCord doesn't allow it either.

**Comment by Jisagi** [comment]
Wow, discord terminates your account and now you complain that you can't access your server. They probably terminated it for a reason. Why should a bot like xenon or xtracord, which do the exact same as my script does btw, help with this "problem"?

**Comment by hithereimxplicit** [comment]
1) They terminated on accident, I've tried to contact support, no response yet. 
2) Source codes can be edited to fix this.

**Comment by Jisagi** [comment]
If it's an accident, then just wait for the support to fix it. I don't see the problem. Why even overwriting a server which already has data on it anway. Why not using a new and clean server?

**Comment by hithereimxplicit** [comment]
Because the server I am trying to do it on is a 11k member server, not trying to start fresh from that. Also support has been taking over 1-2k weeks to respond so this is just the easier way.

**Comment by Jisagi** [comment]
Well, you said it sourself "Source codes can be edited to fix this". Sounds like you already know what to do. I will not change the script just for you and your specific "problem". I cannot verify if your ban was "by accident" or not, therefore wait for the support to fix it, if it actually was by accident.

**Comment by hithereimxplicit** [comment]
If I knew what to do, I wouldn't be asking you. Regardless if my ban was on purpose or by accident, that shouldn't stop a developer from helping someone disable a feature of their script. My account ban didn't really have anything to do with it.

**Comment by Jisagi** [comment]
It's not about disabling a feature but checking what else breaks because the check is not done anymore of it. Your error is one of the many possible problems which will arise now that the check isnt done anymore. this is not aobut a developer helping someone, but more like me personally adjusting my script to your specific problem

**Comment by hithereimxplicit** [comment]
So you wouldn't take time out of your day to someone who enjoys your script and will continue to support you?

**Comment by Jisagi** [comment]
1. I will always make time for something reasonable
2. There is nothing to support me with
3. You can always try to just remove the [role deletion](https://github.com/Jisagi/Discord-guild-copy/blob/master/objects/cleaner.js#L38), but I have no idea how the script starts to behave afterwards. if taht doesn't work, then I can't help anymore
