### ISSUE TITLE
NPM Install issue

### ISSUE THREAD

**Issue by cobe666** [Jisagi/Discord-guild-copy#85]
I am having an issue on when I do npm install, I get a set of errors, screenshot below
![Screenshot_38](https://user-images.githubusercontent.com/54997261/99692867-abb7da00-2a82-11eb-9d72-03a9778c8a86.png)

Please help me, thanks.

**Comment by Jisagi** [comment]
Looks like you're missing git on your computer. Try installing [git for windows](https://git-scm.com/download/win) and then try again. (A restart might be needed after the installation)
