### ISSUE TITLE
error

### ISSUE THREAD

**Issue by actuallydoc** [Jisagi/Discord-guild-copy#87]
Neither a package-lock.json nor a yarn.lock file are present. Please do not delete those

it logs in the bot but i throws the error above and quits

- Node.js version: v14.15.3
- Operating system:Windows 10

**Comment by Jisagi** [comment]
The error is pretty self explanatory. You either didn't download the whole repository, or deleted the files listed in the error message. Redownload the whole repository, install the dependencies again and then try again.

**Comment by actuallydoc** [comment]
package-lock.js is not even in the repository in ur project

**Comment by Jisagi** [comment]
The `package-lock.json` (or `yarn.lock`) file is present **IF YOU INSTALLED THE DEPENDENCIES**. Please do what the instructions tell you
