### ISSUE TITLE
Error when copying roles

### ISSUE THREAD

**Issue by TwistyyyNet** [Jisagi/Discord-guild-copy#89]
**Please describe the problem you are having in detail:** Role names, perms and colors aren't copying. Ending up with "New Role" every time

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

- Node.js version: v14.15.3
- Operating system: Win 10

**Comment by Jisagi** [comment]
Yes, this is a bug. I fixed it in the latest commit. Just redownload the repository and try again
