### ISSUE TITLE
Confusing outcome [help]

### ISSUE THREAD

**Issue by Veilga** [Jisagi/Discord-guild-copy#90]
So, pardon me in advance but i'm not good with these things, i had some problems with the script, but i managed to fix them.
But now, its not showing any mistake, but any successful opperation either. So i am not sure what i'm doing wrong.

![](https://i.imgur.com/NWyu3oa.png)

In case you want additionnal information about the settings :

![](https://i.imgur.com/1WuzZCU.png)

The token comes from a bot i just created, and put in both of my server for good measure.
I'm not sure what i am missing.

Thanks.

- Node.js version: v14.15.4
- Operating system: Win 10 pro

**Comment by Jisagi** [comment]
Use `node copy.js <COMMAND>`
COMMAND: This is either `restore`, `backup` or `clone` as the output already tells you. The backfiles are optional

And I would advise you to change your token now, since you posted it publicly :D

**Comment by Veilga** [comment]
Yes indeed, i completely brainlag. it told me the commands. ( don't worry about the bot, its just here for the cloning :D )

I just had to work around the highest guild role thing to make it to work.
It's all good now! thanks again!
