### ISSUE TITLE
Fixed role creations

### ISSUE THREAD

**Issue by 1nchpp** [Jisagi/Discord-guild-copy#91]
No errors, just a bug fix. In the file "objects/creator.js", the roles come out as new role with no data. Line 150 needs to be changed to this `let createdRole = await newGuild.roles.create({data: newRole});`

I didn't want to take the time for a pull request when it is such a small fix.

**Comment by Jisagi** [comment]
As can be seen [here](https://discord.js.org/#/docs/main/master/class/RoleManager?scrollTo=create), it does not need to be changed and works just fine with the latest/master version of djs
