### ISSUE TITLE
Error: member.hasPermission is not a function

### ISSUE THREAD

**Issue by iQuadCore** [Jisagi/Discord-guild-copy#92]
**Please describe the problem you are having in detail:**

I am trying to run the script in backup mode and I am getting the following error:

> member.hasPermission is not a function

**Additional information:**
Script used to work before 1.5.1 update and discord.js update

- Node.js version: v15.7.0
- Operating system: Ubuntu 20.04.1 LTS

**Comment by Jisagi** [comment]
Yes, this is indeed a bug. I pushed a fix just now. Just redownload the repository and try it again

**Comment by iQuadCore** [comment]
Wow, that was fast. 
Works now, thanks 👍
