### ISSUE TITLE
This is normal?

### ISSUE THREAD

**Issue by DavidGpro** [Jisagi/Discord-guild-copy#94]
![image](https://user-images.githubusercontent.com/47284421/106589413-49805880-654c-11eb-857d-e047633471f5.png)

**Comment by Jisagi** [comment]
You used an incorrect guild id or or the bot isn't member of said guild. Please actually read what it tells you.

**Comment by DavidGpro** [comment]
But it is mandatory that the bot is in the guild to copy it?

**Comment by Jisagi** [comment]
Yes, otherwise you could instantly create a copy of a guild despite not having the permission to do so.

**Comment by DavidGpro** [comment]
ok, thanks
