### ISSUE TITLE
problem when laucnhing

### ISSUE THREAD

**Issue by Chadoxi** [Jisagi/Discord-guild-copy#95]
Hey, when I launch the copy.js, I have this:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'discord.js'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose npm-session e4f91ab2cbd759c7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for discord.js@git://github.com/hydrabolt/discord.js.git#master Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 79ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
10 verbose stack     at onErrorNT (internal/child_process.js:469:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
11 verbose cwd C:\Users\asus\Downloads\Discord-guild-copy-master
12 verbose Windows_NT 10.0.18362
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "discord.js"
14 verbose node v12.18.1
15 verbose npm  v6.14.5
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno ENOENT
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]
help me pls

**Comment by Jisagi** [comment]
Install [git for windows](https://git-scm.com/download/win) and try again
