### ISSUE TITLE
Cannot read property 'version' of undefined.

### ISSUE THREAD

**Issue by Sakiuchi** [Jisagi/Discord-guild-copy#96]
**Please describe the problem you are having in detail:**
Im trying to run it and I followed the steps but its throwing an error.
Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

**Additional information:**

- Node.js version: v14.15.5
- Operating system: windows 10
![Screenshot_1](https://user-images.githubusercontent.com/69994457/107869140-32513d00-6e61-11eb-9776-92832069853a.jpg)
![image](https://user-images.githubusercontent.com/69994457/107869245-60834c80-6e62-11eb-9d26-48d815ab0fca.png)
[errors.log](https://github.com/Jisagi/Discord-guild-copy/files/5977024/errors.log)
[log.log](https://github.com/Jisagi/Discord-guild-copy/files/5977025/log.log)
![Screenshot_2](https://user-images.githubusercontent.com/69994457/107869186-95db6a80-6e61-11eb-8519-4b79fa2e8b11.jpg)

**Comment by Chadoxi** [comment]
Can u show me the line 25 of the copy.js?

**Comment by Jisagi** [comment]
> Can u show me the line 25 of the copy.js?

Line 25 will not help in any way solving this problem. I'm currently on it and fixing other issues as well btw.

@Sakiuchi Seem like he cannot read the `package-lock.json` for some reason, which I cannot replicate. I suppose you exedcute the script from within the project folder, so in theory it should work. You could manually look into your file and search for discord.js. there will be multiple occurrences and one of thejkm should look like the image below:
![image](https://i.imgur.com/HjIfVVJ.png)

**Comment by Chadoxi** [comment]
Jisahi Can I have your Discord? I have a real problem with your software

**Comment by Jisagi** [comment]
> Jisahi Can I have your Discord? I have a real problem with your software

Feel free to open a seperate issue here on github. I don't have an "official" discord server or anything and I usually don't help directly on discord in DMs either.

**Comment by Sakiuchi** [comment]
> > Can u show me the line 25 of the copy.js?
> 
> Line 25 will not help in any way solving this problem. I'm currently on it and fixing other issues as well btw.
> 
> @Sakiuchi Seem like he cannot read the `package-lock.json` for some reason, which I cannot replicate. I suppose you exedcute the script from within the project folder, so in theory it should work. You could manually look into your file and search for discord.js. there will be multiple occurrences and one of thejkm should look like the image below:
> ![image](https://camo.githubusercontent.com/cbb4238ae9e30bd9d12cff01eb407d13b1aec1cf1f481eb56376cc09e0538f19/68747470733a2f2f692e696d6775722e636f6d2f486a496656564a2e706e67)

there is no discord.js in the package-lock file

**Comment by Jisagi** [comment]
That is very interesting. Delete the file and the node_modules folder as well and rerun `npm isntall`. Let's see if that helps

**Comment by Sakiuchi** [comment]
![image](https://user-images.githubusercontent.com/69994457/107889667-a4ba2f80-6eea-11eb-8a80-67f7c15f9b31.png)
maybe this is why?

**Comment by Jisagi** [comment]
Ah yes, that does explain it. Install [git for windows](https://git-scm.com/download/win) and then rerun npm install. Without giot it cannot pull discord.js from github

**Comment by Sakiuchi** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/69994457/107889898-fc0ccf80-6eeb-11eb-8379-db2dba7fca00.jpg)

**Comment by Jisagi** [comment]
Yes, that is something I couldn't fix yet. I'm still waiting on a bug to be fixed in the discord.js library to be able to fix this here. Let's hope it doesnt take too long

**Comment by Sakiuchi** [comment]
Okay ty

**Comment by Chadoxi** [comment]
![image](https://user-images.githubusercontent.com/65661361/107937069-ba2f6800-6f83-11eb-919b-02ea20cb8d5f.png)

I'm blocked at this :/

**Comment by Jisagi** [comment]
> ![image](https://user-images.githubusercontent.com/65661361/107937069-ba2f6800-6f83-11eb-919b-02ea20cb8d5f.png)
> 
> I'm blocked at this :/

As I said before, please open a seperate issue!

**Comment by Jisagi** [comment]
Fixed now, please redownload the repository
