### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Chadoxi** [Jisagi/Discord-guild-copy#97]
Hey, when I launch, I have this:
![image](https://user-images.githubusercontent.com/65661361/107945256-a12cb400-6f8f-11eb-958d-3028a2fc40ae.png)

**Comment by Jisagi** [comment]
Did you cahnge parts of the code? What is the console even spamming at the start, seems like the translator is broken as well. It should never do that, except some cahnges something in the code. Before even starting to restore it shoud already stop when the new guild isn't available.

**Comment by Jisagi** [comment]
Also post a full log of everything the console puts out, especially at the start of the script execution

**Comment by Chadoxi** [comment]
I changed parts of the code because not works :/
But if I take the original I have this:
Microsoft Windows [version 10.0.18362.1256]
(c) 2019 Microsoft Corporation. Tous droits réservés.

C:\Users\asus\Downloads\Discord-guild-copy-master>node copy clone
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- C:\Users\asus\Downloads\Discord-guild-copy-master\copy.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\asus\Downloads\Discord-guild-copy-master\copy.js:3:17)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'C:\\Users\\asus\\Downloads\\Discord-guild-copy-master\\copy.js'[39m ]
}

C:\Users\asus\Downloads\Discord-guild-copy-master>npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/hydrabolt/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2021-02-15T13_53_32_291Z-debug.log

C:\Users\asus\Downloads\Discord-guild-copy-master>

**Comment by Jisagi** [comment]
Well of course nothing works when you rewrite the code. Install [git for windows](https://git-scm.com/download/win) and then run npm isntall as the readme tells you to.

**Comment by Jisagi** [comment]
I clarified this point in the readme as well now by adding git as requirement. Now it should work. Feels free to reopen the ticket if it doesn't
