### ISSUE TITLE
New problem :/

### ISSUE THREAD

**Issue by Chadoxi** [Jisagi/Discord-guild-copy#98]
So, I installed git, and works to install packages, but, when I type "node copy clone", I have this:
Microsoft Windows [version 10.0.18362.1256]
(c) 2019 Microsoft Corporation. Tous droits réservés.

C:\Users\asus\Downloads\Discord-guild-copy-master>node copy clone
C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\discord.js\src\util\Collection.js:8
    return this.map(e => (typeof e?.toJSON === 'function' ? e.toJSON() : Util.flatten(e)));
                                   ^

SyntaxError: Unexpected token '.'
[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\[4mdiscord.js[24m\src\rest\RESTManager.js:7:20)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m

C:\Users\asus\Downloads\Discord-guild-copy-master>

**Comment by Jisagi** [comment]
Either you did not fill out the token in the settings file or the token itelf is not in a valid format

**Comment by Chadoxi** [comment]
The token is valid and in the settings file, idk where is the problem :/

**Comment by Chadoxi** [comment]
Its a problem with the collection.js

**Comment by Jisagi** [comment]
Run `node -v` in an empty console and tell me the version it tells you. Smells like an outdated nodejs version

**Comment by Chadoxi** [comment]
v12.18.1

**Comment by Jisagi** [comment]
Update it to at least v14. Optional chaining `e?.toJSON` with the questionmark is the problem. It a new feature in nodejs v14 and higher

**Comment by Chadoxi** [comment]
Okay, new problem:
Microsoft Windows [version 10.0.18362.1256]
(c) 2019 Microsoft Corporation. Tous droits réservés.

C:\Users\asus\Downloads\Discord-guild-copy-master>node copy
C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\discord.js\src\client\Client.js:461
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\[4mdiscord.js[24m\src\client\Client.js:461:13)
    at new Client (C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\[4mdiscord.js[24m\src\client\Client.js:76:10)
    at Object.<anonymous> (C:\Users\asus\Downloads\Discord-guild-copy-master\copy.js:13:16)
[90m    at Module._compile (node:internal/modules/cjs/loader:1108:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:973:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)[39m
[90m    at node:internal/main/run_main_module:17:47[39m {
  [[32mSymbol(code)[39m]: [32m'CLIENT_MISSING_INTENTS'[39m
}

C:\Users\asus\Downloads\Discord-guild-copy-master>node copy clone
C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\discord.js\src\client\Client.js:461
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\[4mdiscord.js[24m\src\client\Client.js:461:13)
    at new Client (C:\Users\asus\Downloads\Discord-guild-copy-master\node_modules\[4mdiscord.js[24m\src\client\Client.js:76:10)
    at Object.<anonymous> (C:\Users\asus\Downloads\Discord-guild-copy-master\copy.js:13:16)
[90m    at Module._compile (node:internal/modules/cjs/loader:1108:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:973:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)[39m
[90m    at node:internal/main/run_main_module:17:47[39m {
  [[32mSymbol(code)[39m]: [32m'CLIENT_MISSING_INTENTS'[39m
}

C:\Users\asus\Downloads\Discord-guild-copy-master>

**Comment by Jisagi** [comment]
Yes, now we are at the same problem everyone will face currently. I am sadly still waiting on a bugfix in the discord.js library. Before taht isn't fixed I cannot push my fix, so we have to wait for now. I will update this issue when I fixed it

**Comment by Chadoxi** [comment]
oki

**Comment by Jisagi** [comment]
Fixed now, please redownload the repository
